In [10]:
import pandas as pd
import numpy as np

In [11]:
%%time
train_df = pd.read_csv('./data/train.csv')

CPU times: user 38.7 s, sys: 14.7 s, total: 53.4 s
Wall time: 1min 4s

In [12]:
train_df.head()

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4

In [40]:
train_df[train_df.session_id==20090312433251036]

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
881,20090312433251036,0,0,cutscene_click,basic,0,NaN,-394.991405,84.685314,399.0,250.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,0,0-4
882,20090312433251036,1,218,person_click,basic,0,NaN,-394.991405,84.685314,399.0,250.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,0,0-4
883,20090312433251036,2,448,person_click,basic,0,NaN,-394.991405,84.685314,399.0,250.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,0,0-4
884,20090312433251036,3,702,person_click,basic,0,NaN,-394.991405,84.685314,399.0,250.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,0,0-4
885,20090312433251036,4,948,person_click,basic,0,NaN,-394.991405,84.685314,399.0,250.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,0,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2707,20090312433251036,1871,3764520,map_hover,basic,22,NaN,NaN,NaN,NaN,NaN,49.0,NaN,tunic.capitol_2,tunic.historicalsociety.entry,NaN,0,0,0,13-22
2708,20090312433251036,1872,3764686,map_hover,basic,22,NaN,NaN,NaN,NaN,NaN,132.0,NaN,tunic.library,tunic.historicalsociety.entry,NaN,0,0,0,13-22
2709,20090312433251036,1873,3764935,map_click,undefined,22,NaN,476.887585,5.834737,453.0,326.0,NaN,NaN,tunic.capitol_2,tunic.historicalsociety.entry,NaN,0,0,0,13-22
2710,20090312433251036,1874,3813349,navigate_click,undefined,22,NaN,239.341836,-17.844428,414.0,309.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,0,13-22
2711,20090312433251036,1875,3815334,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,0,13-22

In [39]:
label_df = pd.read_csv('./data/train_labels.csv')
isin = np.array([1 if s_id.find('20090312433251036')>=0 else 0 for s_id in label_df.session_id])

label_df[isin==1]

                   session_id  correct
1        20090312433251036_q1        0
23563    20090312433251036_q2        1
47125    20090312433251036_q3        1
70687    20090312433251036_q4        1
94249    20090312433251036_q5        0
117811   20090312433251036_q6        1
141373   20090312433251036_q7        1
164935   20090312433251036_q8        0
188497   20090312433251036_q9        1
212059  20090312433251036_q10        0
235621  20090312433251036_q11        0
259183  20090312433251036_q12        1
282745  20090312433251036_q13        0
306307  20090312433251036_q14        1
329869  20090312433251036_q15        0
353431  20090312433251036_q16        1
376993  20090312433251036_q17        0
400555  20090312433251036_q18        1

In [22]:
train_df.session_id.nunique()

23562

In [38]:
label_df.head()

             session_id  correct
0  20090312431273200_q1        1
1  20090312433251036_q1        0
2  20090312455206810_q1        1
3  20090313091715820_q1        0
4  20090313571836404_q1        1